import { useState, useEffect, useMemo } from "react";

const CONFIG_KEY = "finapp_config";
const TX_KEY = "finapp_transactions";
const SPLIT_KEY = "finapp_splits";
const PAYMENT_KEY = "finapp_split_payments";

function genId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

function today() {
  return new Date().toISOString().slice(0, 10);
}

function formatDate(d) {
  if (!d) return "";
  try {
    return new Date(d + "T00:00:00").toLocaleDateString("th-TH", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return d;
  }
}

function daysUntil(dateStr) {
  if (!dateStr) return null;
  const diff = new Date(dateStr + "T00:00:00") - new Date(today() + "T00:00:00");
  return Math.round(diff / 86400000);
}

function money(n, currency = "THB") {
  const symbol = currency === "THB" ? "฿" : currency === "USD" ? "$" : currency;
  return `${symbol}${Number(n || 0).toLocaleString("th-TH", { maximumFractionDigits: 2 })}`;
}

function Avatar({ person, size = 36 }) {
  const initials = ((person.nickname || person.name) || "?").slice(0, 2).toUpperCase();
  return (
    <div
      style={{
        width: size,
        height: size,
        borderRadius: "50%",
        background: person.color || "#6366f1",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: "#fff",
        fontWeight: 700,
        fontSize: size * 0.35,
        flexShrink: 0,
        overflow: "hidden",
      }}
    >
      {person.avatarUrl ? (
        <img src={person.avatarUrl} alt={person.name} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
      ) : (
        initials
      )}
    </div>
  );
}

function Badge({ color, children, style = {} }) {
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        padding: "2px 9px",
        borderRadius: 99,
        fontSize: 11,
        fontWeight: 600,
        background: color + "18",
        color,
        border: `1px solid ${color}33`,
        ...style,
      }}
    >
      {children}
    </span>
  );
}

function Pill({ active, onClick, color, children }) {
  return (
    <button
      onClick={onClick}
      style={{
        padding: "5px 14px",
        borderRadius: 99,
        fontSize: 12,
        fontWeight: 500,
        border: `1.5px solid ${active ? color : "#e5e7eb"}`,
        background: active ? color + "15" : "#fff",
        color: active ? color : "#9ca3af",
        cursor: "pointer",
        transition: "all 0.15s",
        whiteSpace: "nowrap",
      }}
    >
      {children}
    </button>
  );
}

function ProgressBar({ value, max, color = "#6366f1", height = 8 }) {
  const pct = max > 0 ? Math.min(100, (value / max) * 100) : 0;
  return (
    <div style={{ background: "#f3f4f6", borderRadius: 99, height, overflow: "hidden" }}>
      <div
        style={{
          width: `${pct}%`,
          height: "100%",
          background: color,
          borderRadius: 99,
          transition: "width 0.4s ease",
        }}
      />
    </div>
  );
}

function getAllPeople(config) {
  return [{ id: "self", name: config.profile?.name || "ฉัน", color: "#6366f1", nickname: "Me" }, ...(config.people || [])];
}

function getSplitPaidAmount(payments, splitId, personId) {
  return payments
    .filter((p) => p.splitId === splitId && p.personId === personId)
    .reduce((sum, p) => sum + Number(p.amount || 0), 0);
}

function hydrateSplit(split, payments) {
  return {
    ...split,
    participants: (split.participants || []).map((participant) => {
      const paid = getSplitPaidAmount(payments, split.id, participant.personId);
      const actualAmount = Number(participant.actualAmount || 0);
      const delta = actualAmount - paid;
      return {
        ...participant,
        actualAmount,
        paidAmount: paid,
        remainingAmount: Math.max(0, delta),
        overpaidAmount: Math.max(0, -delta),
        isPaidFull: paid >= actualAmount - 0.01,
        isOverpaid: paid > actualAmount + 0.01,
      };
    }),
  };
}

function buildNamedPayerSplit(tx) {
  return {
    id: `auto_${tx.id}`,
    txId: tx.id,
    dueDate: "",
    note: "auto-generated from named payer",
    autoGenerated: true,
    participants: [
      {
        personId: tx.paidBy,
        mode: "amount",
        value: Number(tx.amount || 0),
        actualAmount: Number(tx.amount || 0),
      },
    ],
  };
}

function SplitEditor({ tx, config, split, onSave, onClose }) {
  const total = Number(tx.amount || 0);
  const currSym = tx.currency === "THB" ? "฿" : tx.currency === "USD" ? "$" : tx.currency;

  const [participants, setParticipants] = useState(() => {
    if (split?.participants?.length) {
      return split.participants.map((p) => ({
        ...p,
        value: p.value === 0 ? "" : p.value,
      }));
    }
    return [{ personId: "self", mode: "amount", value: "" }];
  });
  const [dueDate, setDueDate] = useState(split?.dueDate || "");
  const [note, setNote] = useState(split?.note || "");
  const [inputMode, setInputMode] = useState(split?.participants?.[0]?.mode || "amount");

  const allPeople = getAllPeople(config);

  const addPerson = (pid) => {
    if (!pid) return;
    if (participants.find((p) => p.personId === pid)) return;
    setParticipants((ps) => [...ps, { personId: pid, mode: inputMode, value: "" }]);
  };

  const removePerson = (pid) => {
    setParticipants((ps) => ps.filter((p) => p.personId !== pid));
  };

  const updateValue = (pid, val) => {
    setParticipants((ps) =>
      ps.map((p) => (p.personId === pid ? { ...p, value: val === "" ? "" : val, mode: inputMode } : p)),
    );
  };

  const resolved = useMemo(() => {
    const deduped = participants.filter((p, index, arr) => arr.findIndex((x) => x.personId === p.personId) === index);
    if (inputMode === "percent") {
      return deduped.map((p) => ({ ...p, actualAmount: (Number(p.value || 0) / 100) * total }));
    }
    return deduped.map((p) => ({ ...p, actualAmount: Number(p.value || 0) }));
  }, [participants, inputMode, total]);

  const sumAssigned = resolved.reduce((s, p) => s + Number(p.actualAmount || 0), 0);
  const remaining = total - sumAssigned;
  const isBalanced = Math.abs(remaining) < 0.01;

  const autoSplit = () => {
    const n = participants.length;
    if (!n) return;

    if (inputMode === "percent") {
      const each = parseFloat((100 / n).toFixed(2));
      setParticipants((ps) =>
        ps.map((p, i) => ({
          ...p,
          value: i === n - 1 ? Number((100 - each * (n - 1)).toFixed(2)) : each,
          mode: "percent",
        })),
      );
    } else {
      const each = parseFloat((total / n).toFixed(2));
      setParticipants((ps) =>
        ps.map((p, i) => ({
          ...p,
          value: i === n - 1 ? Number((total - each * (n - 1)).toFixed(2)) : each,
          mode: "amount",
        })),
      );
    }
  };

  const handleSave = () => {
    const uniqueParticipants = resolved.filter((p, index, arr) => arr.findIndex((x) => x.personId === p.personId) === index);
    onSave({
      txId: tx.id,
      dueDate,
      note,
      autoGenerated: false,
      participants: uniqueParticipants.map((p) => ({
        personId: p.personId,
        mode: inputMode,
        value: Number(p.value || 0),
        actualAmount: Number(p.actualAmount || 0),
      })),
    });
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.45)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 100,
        padding: 16,
      }}
    >
      <div
        style={{
          background: "#fff",
          borderRadius: 20,
          maxWidth: 480,
          width: "100%",
          boxShadow: "0 24px 80px rgba(0,0,0,0.25)",
          overflow: "hidden",
          maxHeight: "90vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div style={{ background: "linear-gradient(135deg,#1a1a2e,#16213e)", padding: "16px 20px" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
            <div>
              <h3 style={{ margin: "0 0 4px", fontSize: 15, fontWeight: 700, color: "#fff" }}>✂️ แบ่งค่าใช้จ่าย</h3>
              <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.6)" }}>
                {tx.subCat || tx.mainCat} · {formatDate(tx.date)}
              </p>
            </div>
            <div style={{ textAlign: "right" }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: "#ef4444" }}>{currSym}{total.toLocaleString("th-TH", { maximumFractionDigits: 2 })}</div>
              <div style={{ fontSize: 11, color: "rgba(255,255,255,0.5)" }}>{tx.currency}</div>
            </div>
          </div>
        </div>

        <div style={{ overflowY: "auto", flex: 1, padding: "16px 20px" }}>
          <div style={{ display: "flex", gap: 8, marginBottom: 16, alignItems: "center", flexWrap: "wrap" }}>
            <span style={{ fontSize: 12, color: "#6b7280", fontWeight: 600 }}>โหมด:</span>
            {["amount", "percent"].map((mode) => (
              <Pill key={mode} active={inputMode === mode} onClick={() => setInputMode(mode)} color="#6366f1">
                {mode === "amount" ? "💰 จำนวนเงิน" : "% เปอร์เซ็นต์"}
              </Pill>
            ))}
            <button
              onClick={autoSplit}
              style={{
                marginLeft: "auto",
                padding: "5px 12px",
                borderRadius: 8,
                fontSize: 11,
                fontWeight: 600,
                background: "#f0f9ff",
                border: "1.5px solid #bae6fd",
                color: "#0369a1",
                cursor: "pointer",
              }}
            >
              ⚡ หารเท่าๆ
            </button>
          </div>

          <div style={{ marginBottom: 14 }}>
            <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 6, letterSpacing: "0.04em", textTransform: "uppercase" }}>
              เพิ่มผู้ร่วมจ่าย
            </label>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {allPeople
                .filter((person) => !participants.find((pt) => pt.personId === person.id))
                .map((person) => (
                  <button
                    key={person.id}
                    onClick={() => addPerson(person.id)}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 6,
                      padding: "6px 12px",
                      borderRadius: 99,
                      fontSize: 12,
                      fontWeight: 500,
                      border: "1.5px solid #e5e7eb",
                      background: "#fff",
                      cursor: "pointer",
                      color: "#374151",
                    }}
                  >
                    <Avatar person={person} size={20} />
                    {person.nickname || person.name}
                  </button>
                ))}
            </div>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 16 }}>
            {resolved.map((participant) => {
              const person = allPeople.find((p) => p.id === participant.personId) || { name: participant.personId, color: "#9ca3af" };
              const pct = total > 0 ? (participant.actualAmount / total) * 100 : 0;
              return (
                <div
                  key={participant.personId}
                  style={{
                    background: "#f9fafb",
                    borderRadius: 12,
                    padding: "12px 14px",
                    border: "1.5px solid #f3f4f6",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
                    <Avatar person={person} size={32} />
                    <span style={{ flex: 1, fontWeight: 600, fontSize: 13, color: "#1a1a2e" }}>{person.name}</span>
                    <div style={{ fontWeight: 700, fontSize: 14, color: "#1a1a2e" }}>
                      {currSym}{Number(participant.actualAmount || 0).toLocaleString("th-TH", { maximumFractionDigits: 2 })}
                      <span style={{ fontSize: 11, color: "#9ca3af", marginLeft: 4 }}>({pct.toFixed(1)}%)</span>
                    </div>
                    {participant.personId !== "self" && (
                      <button
                        onClick={() => removePerson(participant.personId)}
                        style={{
                          width: 24,
                          height: 24,
                          borderRadius: "50%",
                          background: "#fef2f2",
                          border: "none",
                          cursor: "pointer",
                          color: "#ef4444",
                          fontSize: 14,
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                      >
                        ×
                      </button>
                    )}
                  </div>
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <input
                      type="number"
                      value={participant.value}
                      onChange={(e) => updateValue(participant.personId, e.target.value)}
                      min={0}
                      max={inputMode === "percent" ? 100 : total}
                      style={{
                        flex: 1,
                        padding: "7px 10px",
                        borderRadius: 8,
                        border: "1.5px solid #e5e7eb",
                        fontSize: 13,
                        fontFamily: "inherit",
                        outline: "none",
                      }}
                    />
                    <span style={{ fontSize: 12, color: "#9ca3af", minWidth: 20 }}>{inputMode === "percent" ? "%" : tx.currency}</span>
                  </div>
                  <div style={{ marginTop: 8 }}>
                    <ProgressBar value={participant.actualAmount} max={total} color={person.color || "#6366f1"} height={4} />
                  </div>
                </div>
              );
            })}
          </div>

          <div
            style={{
              padding: "10px 14px",
              borderRadius: 10,
              marginBottom: 14,
              background: isBalanced ? "#f0fdf4" : "#fef9ec",
              border: `1px solid ${isBalanced ? "#bbf7d0" : "#fde68a"}`,
              display: "flex",
              alignItems: "center",
              gap: 8,
            }}
          >
            <span style={{ fontSize: 16 }}>{isBalanced ? "✅" : "⚠️"}</span>
            <div style={{ flex: 1 }}>
              <span style={{ fontSize: 13, fontWeight: 600, color: isBalanced ? "#15803d" : "#92400e" }}>
                {isBalanced ? "ยอดครบแล้ว!" : `ยังขาดอยู่ ${currSym}${Math.abs(remaining).toLocaleString("th-TH", { maximumFractionDigits: 2 })}`}
              </span>
              <div style={{ fontSize: 11, color: isBalanced ? "#16a34a" : "#b45309", marginTop: 2 }}>
                แบ่งไปแล้ว {currSym}{sumAssigned.toLocaleString("th-TH", { maximumFractionDigits: 2 })} / {currSym}{total.toLocaleString("th-TH", { maximumFractionDigits: 2 })}
              </div>
            </div>
          </div>

          <div style={{ display: "flex", gap: 12, marginBottom: 16 }}>
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 4, letterSpacing: "0.04em", textTransform: "uppercase" }}>
                วันครบกำหนดชำระ
              </label>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                style={{ width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #e5e7eb", fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box" }}
              />
            </div>
            <div style={{ flex: 1 }}>
              <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 4, letterSpacing: "0.04em", textTransform: "uppercase" }}>
                หมายเหตุ
              </label>
              <input
                type="text"
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="บันทึกเพิ่มเติม..."
                style={{ width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #e5e7eb", fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box" }}
              />
            </div>
          </div>
        </div>

        <div style={{ padding: "12px 20px 20px", borderTop: "1px solid #f3f4f6", display: "flex", gap: 10 }}>
          <button
            onClick={onClose}
            style={{
              flex: 1,
              padding: "11px",
              borderRadius: 10,
              border: "1.5px solid #e5e7eb",
              background: "#fff",
              fontSize: 13,
              fontWeight: 600,
              color: "#6b7280",
              cursor: "pointer",
            }}
          >
            ยกเลิก
          </button>
          <button
            onClick={handleSave}
            disabled={!isBalanced}
            style={{
              flex: 2,
              padding: "11px",
              borderRadius: 10,
              border: "none",
              background: isBalanced ? "#6366f1" : "#e5e7eb",
              fontSize: 13,
              fontWeight: 700,
              color: isBalanced ? "#fff" : "#9ca3af",
              cursor: isBalanced ? "pointer" : "not-allowed",
            }}
          >
            💾 บันทึกการแบ่ง
          </button>
        </div>
      </div>
    </div>
  );
}

function RecordPaymentModal({ split, tx, personId, config, existingPayments, onSave, onUpdatePayment, onDeletePaymentRequest, onClose }) {
  const allPeople = getAllPeople(config);
  const person = allPeople.find((p) => p.id === personId) || { name: personId };
  const participant = (split.participants || []).find((p) => p.personId === personId);
  const owed = Number(participant?.actualAmount || 0);
  const myPayments = existingPayments.filter((p) => p.splitId === split.id && p.personId === personId);
  const paid = myPayments.reduce((s, p) => s + Number(p.amount || 0), 0);
  const remaining = Math.max(0, owed - paid);
  const isPaidFull = remaining <= 0.01;
  const currSym = tx?.currency === "THB" ? "฿" : tx?.currency || "฿";

  const [editingId, setEditingId] = useState(null);
  const [amount, setAmount] = useState(remaining > 0 ? remaining.toFixed(2) : "");
  const [date, setDate] = useState(today());
  const [note, setNote] = useState("");

  const startEdit = (payment) => {
    setEditingId(payment.id);
    setAmount(String(payment.amount));
    setDate(payment.date);
    setNote(payment.note || "");
  };

  const cancelEdit = () => {
    setEditingId(null);
    setAmount(remaining > 0 ? remaining.toFixed(2) : "");
    setDate(today());
    setNote("");
  };

  const maxEditable = editingId
    ? Math.max(
        0,
        owed - myPayments.filter((p) => p.id !== editingId).reduce((s, p) => s + Number(p.amount || 0), 0),
      )
    : remaining;

  const handleSubmit = () => {
    const val = parseFloat(amount) || 0;
    if (val <= 0) return;

    if (editingId) {
      const capped = Math.min(val, maxEditable);
      onUpdatePayment({ id: editingId, splitId: split.id, personId, amount: capped, date, note, createdAt: Date.now() });
    } else {
      const capped = Math.min(val, remaining);
      onSave({ id: genId(), splitId: split.id, personId, amount: capped, date, note, createdAt: Date.now() });
    }

    setEditingId(null);
    setAmount(remaining > 0 ? remaining.toFixed(2) : "");
    setNote("");
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.45)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 200,
        padding: 16,
      }}
    >
      <div
        style={{
          background: "#fff",
          borderRadius: 16,
          maxWidth: 400,
          width: "100%",
          boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
          overflow: "hidden",
          maxHeight: "90vh",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div style={{ padding: "16px 20px", borderBottom: "1px solid #f3f4f6" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
            <Avatar person={person} size={40} />
            <div style={{ flex: 1 }}>
              <h3 style={{ margin: 0, fontSize: 15, fontWeight: 700 }}>การชำระของ {person.name}</h3>
              <p style={{ margin: 0, fontSize: 12, color: "#6b7280" }}>{tx?.subCat || tx?.mainCat || "รายการ"}</p>
            </div>
            <button onClick={onClose} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 20, color: "#9ca3af" }}>×</button>
          </div>
        </div>

        <div style={{ overflowY: "auto", flex: 1, padding: "16px 20px" }}>
          <div style={{ background: "#f9fafb", borderRadius: 10, padding: "10px 14px", marginBottom: 16 }}>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: "#6b7280", marginBottom: 3 }}>
              <span>ยอดที่ต้องจ่าย</span>
              <span style={{ fontWeight: 600, color: "#1a1a2e" }}>{currSym}{owed.toLocaleString("th-TH", { maximumFractionDigits: 2 })}</span>
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: "#6b7280", marginBottom: 3 }}>
              <span>จ่ายแล้วรวม</span>
              <span style={{ fontWeight: 600, color: "#22c55e" }}>{currSym}{paid.toLocaleString("th-TH", { maximumFractionDigits: 2 })}</span>
            </div>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, borderTop: "1px solid #e5e7eb", paddingTop: 6, marginTop: 4 }}>
              <span style={{ fontWeight: 600 }}>คงค้าง</span>
              <span style={{ fontWeight: 700, color: isPaidFull ? "#22c55e" : "#ef4444" }}>
                {isPaidFull ? "✅ ชำระครบแล้ว" : `${currSym}${remaining.toLocaleString("th-TH", { maximumFractionDigits: 2 })}`}
              </span>
            </div>
            {owed > 0 && (
              <div style={{ marginTop: 8 }}>
                <ProgressBar value={paid} max={owed} color={isPaidFull ? "#22c55e" : person.color || "#6366f1"} height={5} />
              </div>
            )}
          </div>

          {myPayments.length > 0 && (
            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 8, letterSpacing: "0.04em", textTransform: "uppercase" }}>ประวัติการชำระ</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                {myPayments.map((payment) => (
                  <div
                    key={payment.id}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: 10,
                      background: editingId === payment.id ? "#fef9ec" : "#f9fafb",
                      borderRadius: 10,
                      padding: "8px 12px",
                      border: `1px solid ${editingId === payment.id ? "#fde68a" : "#f3f4f6"}`,
                    }}
                  >
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontWeight: 600, fontSize: 13, color: "#1a1a2e" }}>{currSym}{Number(payment.amount || 0).toLocaleString("th-TH", { maximumFractionDigits: 2 })}</div>
                      <div style={{ fontSize: 11, color: "#9ca3af" }}>{formatDate(payment.date)}{payment.note ? ` · ${payment.note}` : ""}</div>
                    </div>
                    <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                    <button
                      onClick={() => (editingId === payment.id ? cancelEdit() : startEdit(payment))}
                      style={{
                        padding: "4px 10px",
                        borderRadius: 7,
                        fontSize: 11,
                        fontWeight: 600,
                        background: editingId === payment.id ? "#fef9ec" : "#f0f0ff",
                        border: `1px solid ${editingId === payment.id ? "#fde68a" : "#c7d2fe"}`,
                        color: editingId === payment.id ? "#92400e" : "#6366f1",
                        cursor: "pointer",
                      }}
                    >
                      {editingId === payment.id ? "ยกเลิก" : "✏️ แก้"}
                    </button>
                    <button
                      onClick={() => {
                        if (editingId === payment.id) cancelEdit();
                        onDeletePaymentRequest(payment.id);
                      }}
                      style={{
                        padding: "4px 10px",
                        borderRadius: 7,
                        fontSize: 11,
                        fontWeight: 600,
                        background: "#fef2f2",
                        border: "1px solid #fecaca",
                        color: "#dc2626",
                        cursor: "pointer",
                      }}
                    >
                      🗑️ ลบ
                    </button>
                  </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {!isPaidFull || editingId ? (
            <div>
              <div style={{ fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 8, letterSpacing: "0.04em", textTransform: "uppercase" }}>
                {editingId ? "แก้ไขรายการชำระ" : "บันทึกการชำระใหม่"}
              </div>
              <div style={{ marginBottom: 10 }}>
                <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 4 }}>
                  จำนวนที่ชำระ (สูงสุด {currSym}{maxEditable.toFixed(2)})
                </label>
                <input
                  type="number"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  max={maxEditable}
                  min={0}
                  step="0.01"
                  style={{ width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #e5e7eb", fontSize: 14, fontFamily: "inherit", outline: "none", boxSizing: "border-box", fontWeight: 600 }}
                />
              </div>
              <div style={{ display: "flex", gap: 10, marginBottom: 14 }}>
                <div style={{ flex: 1 }}>
                  <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 4 }}>วันที่ชำระ</label>
                  <input
                    type="date"
                    value={date}
                    onChange={(e) => setDate(e.target.value)}
                    style={{ width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #e5e7eb", fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box" }}
                  />
                </div>
                <div style={{ flex: 1 }}>
                  <label style={{ display: "block", fontSize: 11, fontWeight: 600, color: "#6b7280", marginBottom: 4 }}>หมายเหตุ</label>
                  <input
                    type="text"
                    value={note}
                    onChange={(e) => setNote(e.target.value)}
                    placeholder="โอน / เงินสด..."
                    style={{ width: "100%", padding: "9px 12px", borderRadius: 8, border: "1.5px solid #e5e7eb", fontSize: 13, fontFamily: "inherit", outline: "none", boxSizing: "border-box" }}
                  />
                </div>
              </div>
              <button
                onClick={handleSubmit}
                style={{
                  width: "100%",
                  padding: "11px",
                  borderRadius: 10,
                  border: "none",
                  background: editingId ? "#f59e0b" : "#22c55e",
                  fontSize: 13,
                  fontWeight: 700,
                  color: "#fff",
                  cursor: "pointer",
                }}
              >
                {editingId ? "💾 บันทึกการแก้ไข" : "✅ บันทึกการชำระ"}
              </button>
            </div>
          ) : (
            <div style={{ padding: "14px", background: "#f0fdf4", borderRadius: 10, textAlign: "center", border: "1px solid #bbf7d0" }}>
              <div style={{ fontSize: 24, marginBottom: 4 }}>✅</div>
              <div style={{ fontWeight: 600, fontSize: 13, color: "#15803d" }}>ชำระครบแล้ว</div>
              <div style={{ fontSize: 12, color: "#16a34a", marginTop: 2 }}>เพิ่มรายการชำระใหม่ไม่ได้ แต่แก้ไข record เดิมได้จากประวัติด้านบน</div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function PersonDebtCard({ person, hydratedSplits, transactions, payments, onRecordPayment, onPayAll }) {
  const allSplitsForPerson = hydratedSplits.filter((split) => (split.participants || []).find((participant) => participant.personId === person.id));
  const totalOwed = allSplitsForPerson.reduce((sum, split) => {
    const participant = split.participants.find((p) => p.personId === person.id);
    return sum + Number(participant?.actualAmount || 0);
  }, 0);
  const totalPaid = allSplitsForPerson.reduce((sum, split) => {
    const participant = split.participants.find((p) => p.personId === person.id);
    return sum + Number(participant?.paidAmount || 0);
  }, 0);
  const totalOverpaid = allSplitsForPerson.reduce((sum, split) => {
    const participant = split.participants.find((p) => p.personId === person.id);
    return sum + Number(participant?.overpaidAmount || 0);
  }, 0);
  const remaining = Math.max(0, totalOwed - totalPaid);
  const hasExpenses = allSplitsForPerson.length > 0;
  const hasOverpaid = totalOverpaid > 0.01;
  const isPaid = hasExpenses && remaining <= 0.01 && !hasOverpaid;

  return (
    <div
      style={{
        background: "#fff",
        borderRadius: 16,
        border: `2px solid ${!hasExpenses ? "#f3f4f6" : hasOverpaid ? "#fecaca" : isPaid ? "#bbf7d0" : (person.color || "#6366f1") + "40"}`,
        padding: "16px",
        overflow: "hidden",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: hasExpenses ? 14 : 0 }}>
        <Avatar person={person} size={48} />
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700, fontSize: 15, color: "#1a1a2e" }}>{person.name}</div>
          {person.nickname && <div style={{ fontSize: 12, color: "#9ca3af" }}>{person.nickname}</div>}
        </div>
        {!hasExpenses ? (
          <Badge color="#9ca3af">ไม่มีค่าใช้จ่าย</Badge>
        ) : hasOverpaid ? (
          <Badge color="#ef4444">⚠️ จ่ายเกิน ฿{Math.round(totalOverpaid).toLocaleString()}</Badge>
        ) : isPaid ? (
          <Badge color="#22c55e">✅ ชำระครบ</Badge>
        ) : (
          <Badge color="#ef4444">คงค้าง ฿{Math.round(remaining).toLocaleString()}</Badge>
        )}
      </div>

      {!hasExpenses && (
        <div style={{ marginTop: 12, padding: "10px 12px", background: "#f9fafb", borderRadius: 10, textAlign: "center" }}>
          <p style={{ margin: 0, fontSize: 12, color: "#9ca3af" }}>ไม่ได้มีค่าใช้จ่ายสำหรับ{person.name}</p>
        </div>
      )}

      {hasExpenses && (
        <>
          <div style={{ marginBottom: 12 }}>
            <div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: "#6b7280", marginBottom: 4 }}>
              <span>{hasOverpaid ? `จ่ายเกิน ฿${Math.round(totalOverpaid).toLocaleString()}` : `จ่ายแล้ว ฿${Math.round(totalPaid).toLocaleString()} / ฿${Math.round(totalOwed).toLocaleString()}`}</span>
              <span style={{ fontWeight: 600, color: hasOverpaid ? "#ef4444" : person.color || "#6366f1" }}>{hasOverpaid ? "ต้องปรับยอด" : `${Math.round(Math.min(100, (totalPaid / Math.max(totalOwed, 1)) * 100))}%`}</span>
            </div>
            <ProgressBar value={hasOverpaid ? totalOwed : totalPaid} max={Math.max(totalOwed, 1)} color={hasOverpaid ? "#ef4444" : isPaid ? "#22c55e" : person.color || "#6366f1"} height={8} />
          </div>

          {hasOverpaid && (
            <div style={{ marginBottom: 12, padding: "10px 12px", background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 10, fontSize: 12, color: "#b91c1c", fontWeight: 600 }}>
              ⚠️ คนนี้จ่ายเกินหลังจากมีการปรับสัดส่วนใหม่ กรุณาตรวจสอบและแก้ไข record การชำระของรายการด้านล่าง
            </div>
          )}

          {!isPaid && !hasOverpaid && (
            <button
              onClick={() => onPayAll(person.id)}
              style={{
                width: "100%",
                marginBottom: 12,
                padding: "9px 12px",
                borderRadius: 10,
                background: "#22c55e",
                border: "none",
                color: "#fff",
                fontSize: 12,
                fontWeight: 700,
                cursor: "pointer",
              }}
            >
              ✅ จ่ายครบทุกค้างของ {person.name}
            </button>
          )}

          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {allSplitsForPerson.map((split) => {
              const tx = transactions.find((t) => t.id === split.txId);
              const participant = split.participants.find((p) => p.personId === person.id);
              const partRemaining = Number(participant?.remainingAmount || 0);
              const partOverpaid = Number(participant?.overpaidAmount || 0);
              const partPaidFull = Boolean(participant?.isPaidFull) && partOverpaid <= 0.01;
              const due = daysUntil(split.dueDate);

              return (
                <div
                  key={split.id}
                  style={{
                    background: partOverpaid > 0.01 ? "#fef2f2" : partPaidFull ? "#f0fdf4" : "#f9fafb",
                    borderRadius: 10,
                    padding: "10px 12px",
                    border: `1px solid ${partOverpaid > 0.01 ? "#fecaca" : partPaidFull ? "#bbf7d0" : "#f3f4f6"}`,
                  }}
                >
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ fontWeight: 600, fontSize: 12, color: "#374151", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                        {tx?.subCat || tx?.mainCat || "รายการ"}
                      </div>
                      <div style={{ fontSize: 11, color: partOverpaid > 0.01 ? "#ef4444" : "#9ca3af" }}>
                        {formatDate(tx?.date)}
                        {split.dueDate && (
                          <span style={{ color: due !== null && due < 0 && !partPaidFull && partOverpaid <= 0.01 ? "#ef4444" : due !== null && due <= 3 && !partPaidFull && partOverpaid <= 0.01 ? "#f59e0b" : partOverpaid > 0.01 ? "#ef4444" : "#9ca3af" }}>
                            {partOverpaid > 0.01 ? ` · ⚠️ จ่ายเกิน ${Math.round(partOverpaid).toLocaleString()} บาท` : due === null ? "" : due < 0 && !partPaidFull ? ` · ⚠️ เกิน ${Math.abs(due)} วัน` : due === 0 && !partPaidFull ? " · ครบวันนี้!" : due !== null && !partPaidFull ? ` · อีก ${due} วัน` : ""}
                          </span>
                        )}
                      </div>
                    </div>
                    <div style={{ textAlign: "right", flexShrink: 0, marginLeft: 8 }}>
                      <div style={{ fontWeight: 700, fontSize: 13, color: partOverpaid > 0.01 ? "#ef4444" : partPaidFull ? "#22c55e" : "#ef4444" }}>{partOverpaid > 0.01 ? `+฿${Math.round(partOverpaid).toLocaleString()}` : partPaidFull ? "✓" : `฿${Math.round(partRemaining).toLocaleString()}`}</div>
                      <div style={{ fontSize: 10, color: "#9ca3af" }}>/ ฿{Math.round(Number(participant?.actualAmount || 0)).toLocaleString()}</div>
                    </div>
                  </div>
                  <button
                    onClick={() => onRecordPayment(split, person.id)}
                    style={{
                      width: "100%",
                      marginTop: 8,
                      padding: "6px",
                      borderRadius: 8,
                      background: partOverpaid > 0.01 ? "#fef2f2" : partPaidFull ? "#f0fdf4" : "#fff",
                      border: `1.5px solid ${partOverpaid > 0.01 ? "#fecaca" : partPaidFull ? "#bbf7d0" : (person.color || "#6366f1") + "44"}`,
                      color: partOverpaid > 0.01 ? "#dc2626" : partPaidFull ? "#16a34a" : person.color || "#6366f1",
                      fontSize: 11,
                      fontWeight: 600,
                      cursor: "pointer",
                    }}
                  >
                    {partOverpaid > 0.01 ? "⚠️ ตรวจสอบการชำระ" : partPaidFull ? "📋 ดูประวัติการชำระ" : "+ บันทึกการชำระ"}
                  </button>
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}

function TxSplitRow({ tx, split, config, payments, onEdit, onRecordPayment }) {
  const allPeople = getAllPeople(config);
  const currSym = tx.currency === "THB" ? "฿" : tx.currency === "USD" ? "$" : tx.currency;
  const totalPaid = (split?.participants || []).reduce((sum, participant) => sum + Number(participant.paidAmount || 0), 0);
  const totalAssigned = (split?.participants || []).reduce((sum, participant) => sum + Number(participant.actualAmount || 0), 0);
  const isComplete = Boolean(split) && Math.abs(Number(tx.amount || 0) - totalAssigned) < 0.01;
  const due = daysUntil(split?.dueDate);

  return (
    <div style={{ background: "#fff", borderRadius: 14, border: `1.5px solid ${split ? "#e5e7eb" : "#fde68a"}`, padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: split ? 12 : 0 }}>
        <div
          style={{
            width: 40,
            height: 40,
            borderRadius: 10,
            flexShrink: 0,
            background: "#ef444415",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: 18,
          }}
        >
          ✂️
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", marginBottom: 2 }}>
            <div style={{ fontWeight: 700, fontSize: 14, color: "#1a1a2e" }}>{tx.subCat || tx.mainCat || "รายการ"}</div>
            {!split ? <Badge color="#f59e0b" style={{ fontSize: 10 }}>ยังไม่ได้แบ่ง</Badge> : isComplete ? <Badge color="#22c55e" style={{ fontSize: 10 }}>จัดการแบ่งครบแล้ว</Badge> : <Badge color="#f59e0b" style={{ fontSize: 10 }}>ยังแบ่งไม่ครบ</Badge>}
          </div>
          <div style={{ fontSize: 12, color: "#9ca3af" }}>
            {formatDate(tx.date)}
            {tx.remark ? ` · "${tx.remark}"` : ""}
            {split?.dueDate ? <span style={{ marginLeft: 6 }}>ครบ {formatDate(split.dueDate)}</span> : ""}
          </div>
        </div>
        <div style={{ textAlign: "right", flexShrink: 0 }}>
          <div style={{ fontWeight: 800, fontSize: 16, color: "#ef4444" }}>{currSym}{Number(tx.amount || 0).toLocaleString("th-TH", { maximumFractionDigits: 2 })}</div>
          {split?.dueDate && due !== null ? (
            <div style={{ fontSize: 11, fontWeight: 600, color: due < 0 ? "#ef4444" : due <= 3 ? "#f59e0b" : due <= 7 ? "#6366f1" : "#9ca3af", marginTop: 2 }}>
              ⏰ {due < 0 ? `เกิน ${Math.abs(due)} วัน` : due === 0 ? "วันนี้!" : `อีก ${due} วัน`}
            </div>
          ) : null}
        </div>
      </div>

      {split ? (
        <>
          {!isComplete && (
            <div style={{ padding: "6px 10px", background: "#fef9ec", borderRadius: 8, marginBottom: 10, fontSize: 12, color: "#92400e" }}>
              ⚠️ ยังแบ่งไม่ครบ — กดแก้ไขเพื่อตรวจสอบ
            </div>
          )}
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginBottom: 10 }}>
            {(split.participants || []).map((participant) => {
              const person = allPeople.find((p) => p.id === participant.personId) || { name: participant.personId, color: "#9ca3af" };
              const ptPaid = getSplitPaidAmount(payments, split.id, participant.personId);
              const ptRemaining = Math.max(0, Number(participant.actualAmount || 0) - ptPaid);
              const ptOverpaid = Math.max(0, ptPaid - Number(participant.actualAmount || 0));
              const ptDone = ptRemaining <= 0.01 && ptOverpaid <= 0.01;
              return (
                <div
                  key={participant.personId}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 6,
                    padding: "6px 10px 6px 6px",
                    borderRadius: 99,
                    background: ptOverpaid > 0.01 ? "#fef2f2" : ptDone ? "#f0fdf4" : "#f9fafb",
                    border: `1.5px solid ${ptOverpaid > 0.01 ? "#fecaca" : ptDone ? "#bbf7d0" : (person.color || "#e5e7eb") + "44"}`,
                    cursor: ptOverpaid > 0.01 || !ptDone ? "pointer" : "default",
                  }}
                  onClick={() => (ptOverpaid > 0.01 || !ptDone) && onRecordPayment(split, participant.personId)}
                >
                  <Avatar person={person} size={22} />
                  <div>
                    <div style={{ fontSize: 11, fontWeight: 600, color: "#374151", lineHeight: 1.2 }}>{person.nickname || person.name}</div>
                    <div style={{ fontSize: 10, color: ptOverpaid > 0.01 ? "#ef4444" : ptDone ? "#16a34a" : "#ef4444" }}>
                      {ptOverpaid > 0.01 ? `⚠️ เกิน ฿${Math.round(ptOverpaid).toLocaleString()}` : ptDone ? `✓ ฿${Math.round(Number(participant.actualAmount || 0)).toLocaleString()}` : `฿${Math.round(ptRemaining).toLocaleString()} คงค้าง`}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <div style={{ flex: 1 }}>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "#9ca3af", marginBottom: 3 }}>
                <span>รับชำระแล้ว</span>
                <span>{Math.round((totalPaid / Math.max(Number(tx.amount || 0), 1)) * 100)}%</span>
              </div>
              <ProgressBar value={totalPaid} max={Number(tx.amount || 0)} color="#22c55e" height={5} />
            </div>
            <button
              onClick={() => onEdit(tx, split)}
              style={{
                padding: "6px 12px",
                borderRadius: 8,
                fontSize: 11,
                fontWeight: 600,
                background: "#f0f0ff",
                border: "1.5px solid #c7d2fe",
                color: "#6366f1",
                cursor: "pointer",
              }}
            >
              ✏️ แก้ไข
            </button>
          </div>
        </>
      ) : (
        <button
          onClick={() => onEdit(tx, null)}
          style={{
            width: "100%",
            marginTop: 10,
            padding: "9px",
            borderRadius: 10,
            background: "#fffbeb",
            border: "1.5px solid #fde68a",
            color: "#92400e",
            fontSize: 12,
            fontWeight: 600,
            cursor: "pointer",
          }}
        >
          ✂️ เริ่มแบ่งค่าใช้จ่าย
        </button>
      )}
    </div>
  );
}

function SummaryOverview({ hydratedSplits, transactions, payments, statusFilter = "all", onSelectStatus = () => {} }) {
  const stats = useMemo(() => {
    let totalOwed = 0;
    let totalCollected = 0;
    let overpaidParticipants = 0;
    hydratedSplits.forEach((split) => {
      (split.participants || []).forEach((participant) => {
        if (participant.personId !== "self") {
          totalOwed += Number(participant.actualAmount || 0);
          totalCollected += Number(participant.paidAmount || 0);
          if (Number(participant.overpaidAmount || 0) > 0.01) overpaidParticipants += 1;
        }
      });
    });

    const remaining = Math.max(0, totalOwed - totalCollected);

    const sharedTxs = transactions.filter((tx) => tx.paidBy === "shared" || (tx.paidBy && tx.paidBy !== "self" && tx.paidBy !== "shared"));
    const splitMap = Object.fromEntries(hydratedSplits.map((split) => [split.txId, split]));
    const totalShared = sharedTxs.length;
    const splitDone = sharedTxs.filter((tx) => {
      const split = splitMap[tx.id];
      if (!split) return false;
      const totalAssigned = (split.participants || []).reduce((sum, participant) => sum + Number(participant.actualAmount || 0), 0);
      return Math.abs(Number(tx.amount || 0) - totalAssigned) < 0.01;
    }).length;
    const notSplitYet = Math.max(0, totalShared - splitDone);

    const overduePendingItems = hydratedSplits.reduce((count, split) => {
      const overdue = split.dueDate && split.dueDate < today();
      if (!overdue) return count;
      const unpaidParticipants = (split.participants || []).filter((participant) => Number(participant.remainingAmount || 0) > 0.01);
      return count + unpaidParticipants.length;
    }, 0);

    const dueSoonPendingItems = hydratedSplits.reduce((count, split) => {
      const d = daysUntil(split.dueDate);
      if (d === null || d < 0 || d > 7) return count;
      const unpaidParticipants = (split.participants || []).filter((participant) => Number(participant.remainingAmount || 0) > 0.01);
      return count + unpaidParticipants.length;
    }, 0);

    return {
      totalOwed,
      totalCollected,
      remaining,
      splitDone,
      totalShared,
      notSplitYet,
      overduePendingItems,
      dueSoonPendingItems,
      overpaidParticipants,
    };
  }, [hydratedSplits, transactions, payments]);

  const cards = [
    { key: "all", label: "ทั้งหมด", value: transactions.length, color: "#6366f1", icon: "📋" },
    { key: "remaining", label: "ยังคงค้าง", value: `฿${Math.round(stats.remaining).toLocaleString()}`, color: "#ef4444", icon: "⏳" },
    { key: "split_done", label: "แบ่งครบแล้ว", value: `${stats.splitDone}/${stats.totalShared}`, color: stats.splitDone === stats.totalShared && stats.totalShared > 0 ? "#22c55e" : "#f59e0b", icon: "✂️" },
    { key: "not_split", label: "ยังไม่ได้แบ่ง", value: stats.notSplitYet, color: "#f59e0b", icon: "⚠️" },
    { key: "overdue", label: "เกินกำหนดค้างชำระ", value: stats.overduePendingItems, color: "#ef4444", icon: "🚨" },
    { key: "due_soon", label: "ใกล้ครบกำหนด", value: stats.dueSoonPendingItems, color: "#6366f1", icon: "⏰" },
    { key: "overpaid", label: "จ่ายเกิน", value: stats.overpaidParticipants, color: "#ef4444", icon: "⚠️" },
  ];

  return (
    <div style={{ display: "flex", gap: 8, marginBottom: 16, overflowX: "auto", paddingBottom: 4 }}>
      {cards.map((card) => {
        const active = statusFilter === card.key;
        return (
          <button
            key={card.label}
            onClick={() => onSelectStatus(card.key)}
            style={{
              flex: "0 0 auto",
              minWidth: 130,
              background: active ? card.color + "12" : "#fff",
              borderRadius: 12,
              border: `1.5px solid ${active ? card.color : card.color + "30"}`,
              padding: "10px 14px",
              cursor: "pointer",
              textAlign: "left",
            }}
          >
            <div style={{ fontSize: 11, color: active ? card.color : "#9ca3af", marginBottom: 3 }}>{card.label}</div>
            <div style={{ fontSize: 15, fontWeight: 700, color: card.color }}>{card.icon} {card.value}</div>
          </button>
        );
      })}
    </div>
  );
}

export default function SplitPage() {
  const [config, setConfig] = useState({ profile: { baseCurrency: "THB" }, accounts: [], categories: [], goals: [], people: [] });
  const [transactions, setTransactions] = useState([]);
  const [splits, setSplits] = useState([]);
  const [payments, setPayments] = useState([]);
  const [editTarget, setEditTarget] = useState(null);
  const [payTarget, setPayTarget] = useState(null);
  const [deletePaymentId, setDeletePaymentId] = useState(null);
  const [confirmSplitChange, setConfirmSplitChange] = useState(null); // {splitData, affectedPeople: [{name, oldAmt, newAmt}]}
  const [view, setView] = useState("transactions");
  const [filterMonth, setFilterMonth] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [sortBy, setSortBy] = useState("default");

  useEffect(() => {
    try {
      const cfg = localStorage.getItem(CONFIG_KEY);
      if (cfg) setConfig(JSON.parse(cfg));
      const tx = localStorage.getItem(TX_KEY);
      if (tx) setTransactions(JSON.parse(tx));
      const sp = localStorage.getItem(SPLIT_KEY);
      if (sp) setSplits(JSON.parse(sp));
      const pm = localStorage.getItem(PAYMENT_KEY);
      if (pm) setPayments(JSON.parse(pm));
    } catch (error) {
      console.error(error);
    }
  }, []);

    const saveSplits = (data) => {
    setSplits(data);
    try {
      localStorage.setItem(SPLIT_KEY, JSON.stringify(data));
    } catch (error) {
      console.error(error);
    }
  };

  const savePayments = (data) => {
    setPayments(data);
    try {
      localStorage.setItem(PAYMENT_KEY, JSON.stringify(data));
    } catch (error) {
      console.error(error);
    }
  };

  const candidateTransactions = useMemo(() => {
    // Pre-build split dueDate map for month filtering
    const dueDateMap = Object.fromEntries((splits || []).map((s) => [s.txId, s.dueDate || ""]));
    return transactions
      .filter((tx) => tx.paidBy === "shared" || (tx.paidBy && tx.paidBy !== "self" && tx.paidBy !== "shared"))
      .filter((tx) => {
        if (!filterMonth) return true;
        const txInMonth = tx.date?.startsWith(filterMonth);
        const dueInMonth = dueDateMap[tx.id]?.startsWith(filterMonth);
        return txInMonth || dueInMonth;
      })
      .sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  }, [transactions, splits, filterMonth]);

  const normalizedSplits = useMemo(() => {
    const map = new Map((splits || []).map((split) => [split.txId, { ...split }]));
    candidateTransactions.forEach((tx) => {
      if (!map.has(tx.id) && tx.paidBy && tx.paidBy !== "self" && tx.paidBy !== "shared") {
        map.set(tx.id, buildNamedPayerSplit(tx));
      }
    });
    return Array.from(map.values());
  }, [splits, candidateTransactions]);

  const hydratedSplits = useMemo(() => normalizedSplits.map((split) => hydrateSplit(split, payments)), [normalizedSplits, payments]);
  const splitByTxId = useMemo(() => Object.fromEntries(hydratedSplits.map((split) => [split.txId, split])), [hydratedSplits]);

  const filteredTransactions = useMemo(() => {
    let list = candidateTransactions;
    if (statusFilter !== "all") {
      list = candidateTransactions.filter((tx) => {
        const split = splitByTxId[tx.id];
        const due = daysUntil(split?.dueDate);
        const totalAssigned = (split?.participants || []).reduce((sum, participant) => sum + Number(participant.actualAmount || 0), 0);
        const isSplitDone = Boolean(split) && Math.abs(Number(tx.amount || 0) - totalAssigned) < 0.01;
        const hasUnpaid = (split?.participants || []).some((participant) => Number(participant.remainingAmount || 0) > 0.01);
        switch (statusFilter) {
          case "remaining":
            return Boolean(split) && hasUnpaid;
          case "split_done":
            return isSplitDone;
          case "not_split":
            return !split || !isSplitDone;
          case "overdue":
            return Boolean(split?.dueDate) && due !== null && due < 0 && hasUnpaid;
          case "due_soon":
            return Boolean(split?.dueDate) && due !== null && due >= 0 && due <= 7 && hasUnpaid;
          case "overpaid":
            return Boolean(split) && (split.participants || []).some((participant) => Number(participant.overpaidAmount || 0) > 0.01);
          default:
            return true;
        }
      });
    }

    return [...list].sort((a, b) => {
      const splitA = splitByTxId[a.id];
      const splitB = splitByTxId[b.id];
      if (sortBy === "due_soon") {
        const da = daysUntil(splitA?.dueDate);
        const db = daysUntil(splitB?.dueDate);
        const va = da === null ? 99999 : da;
        const vb = db === null ? 99999 : db;
        return va - vb;
      }
      if (sortBy === "remaining_desc") {
        const ra = (splitA?.participants || []).reduce((s, p) => s + Number(p.remainingAmount || 0), 0);
        const rb = (splitB?.participants || []).reduce((s, p) => s + Number(p.remainingAmount || 0), 0);
        return rb - ra;
      }
      return (b.date || "").localeCompare(a.date || "");
    });
  }, [candidateTransactions, splitByTxId, statusFilter, sortBy]);

  // ฟังก์ชันที่ทำการ save จริงๆ หลัง confirm แล้ว (หรือไม่มีการเปลี่ยนยอด)
  const commitSaveSplit = (splitData, paymentsOverride) => {
    const existing = normalizedSplits.find((split) => split.txId === splitData.txId);
    const withId = {
      ...splitData,
      id: existing?.id || splitData.id || genId(),
      autoGenerated: false,
    };

    // ใช้ paymentsOverride ถ้ามี (กรณีผ่าน confirm แล้ว), ไม่งั้นใช้ payments ปัจจุบัน
    const currentPayments = paymentsOverride ?? payments;
    if (existing) {
      const oldParticipantIds = new Set((existing.participants || []).map((p) => p.personId));
      const newParticipantIds = new Set((splitData.participants || []).map((p) => p.personId));
      const paymentsToKeep = currentPayments.filter((payment) => {
        if (payment.splitId !== existing.id) return true;
        return newParticipantIds.has(payment.personId) || !oldParticipantIds.has(payment.personId);
      });
      if (paymentsToKeep.length !== currentPayments.length) {
        savePayments(paymentsToKeep);
      }
    }

    const next = existing
      ? splits.some((split) => split.txId === splitData.txId)
        ? splits.map((split) => (split.txId === splitData.txId ? withId : split))
        : [...splits, withId]
      : [...splits, withId];

    saveSplits(next);
    setEditTarget(null);
    setConfirmSplitChange(null);
  };

  const handleSaveSplit = (splitData) => {
    const existing = normalizedSplits.find((split) => split.txId === splitData.txId);

    if (!existing) {
      // Split ใหม่ ไม่มี payment เก่า — save ได้เลย
      commitSaveSplit(splitData);
      return;
    }

    const allPeople = getAllPeople(config);

    // หา participants ที่ยอดเปลี่ยน และมี payment แล้วบางส่วน
    const affectedPeople = [];
    (splitData.participants || []).forEach((newPt) => {
      const oldPt = (existing.participants || []).find((p) => p.personId === newPt.personId);
      if (!oldPt) return; // คนใหม่ — ไม่มี payment เก่า ไม่ต้อง confirm
      const amountChanged = Math.abs(Number(oldPt.actualAmount || 0) - Number(newPt.actualAmount || 0)) > 0.01;
      if (!amountChanged) return;
      const hasPaid = payments.some((pm) => pm.splitId === existing.id && pm.personId === newPt.personId);
      if (!hasPaid) return; // ยังไม่ได้จ่าย — ไม่ต้อง confirm
      const person = allPeople.find((p) => p.id === newPt.personId) || { name: newPt.personId };
      affectedPeople.push({
        personId: newPt.personId,
        name: person.name,
        oldAmt: Number(oldPt.actualAmount || 0),
        newAmt: Number(newPt.actualAmount || 0),
      });
    });

    if (affectedPeople.length === 0) {
      // ไม่มีใครที่ยอดเปลี่ยนและจ่ายแล้ว — save ได้เลย
      commitSaveSplit(splitData);
      return;
    }

    // มีคนที่ยอดเปลี่ยนและจ่ายแล้ว — ถามก่อน
    setConfirmSplitChange({ splitData, affectedPeople });
  };

  const handleSavePayment = (payment) => {
    savePayments([...payments, payment]);
    setPayTarget(null);
  };

  const handleUpdatePayment = (updated) => {
    savePayments(payments.map((payment) => (payment.id === updated.id ? updated : payment)));
    setPayTarget(null);
  };

  const handleDeletePayment = (paymentId) => {
    savePayments(payments.filter((payment) => payment.id !== paymentId));
    if (payTarget) setPayTarget(null);
    setDeletePaymentId(null);
  };

  const handlePayAllForPerson = (personId) => {
    const targetSplits = hydratedSplits.filter((split) => (split.participants || []).some((participant) => participant.personId === personId && Number(participant.remainingAmount || 0) > 0.01));
    if (!targetSplits.length) return;

    const newPayments = targetSplits.flatMap((split) => {
      const participant = split.participants.find((p) => p.personId === personId);
      const remaining = Number(participant?.remainingAmount || 0);
      if (remaining <= 0.01) return [];
      return [
        {
          id: genId(),
          splitId: split.id,
          personId,
          amount: Number(remaining.toFixed(2)),
          date: today(),
          note: "จ่ายครบทุกค้างจาก dashboard",
          createdAt: Date.now(),
        },
      ];
    });

    if (!newPayments.length) return;
    savePayments([...payments, ...newPayments]);
  };

  const monthOptions = Array.from({ length: 12 }, (_, i) => {
    const now = new Date();
    const d = new Date(now.getFullYear(), i, 1);
    return {
      value: `${now.getFullYear()}-${String(i + 1).padStart(2, "0")}`,
      label: d.toLocaleString("th-TH", { month: "long", year: "numeric" }),
    };
  });

  const peopleOnly = getAllPeople(config);

  const filteredPeople = useMemo(() => {
    const list = peopleOnly.filter((person) => {
      const splitsForPerson = hydratedSplits.filter((split) =>
        (split.participants || []).some((participant) => participant.personId === person.id),
      );

      const totalOwed = splitsForPerson.reduce((sum, split) => {
        const participant = (split.participants || []).find((p) => p.personId === person.id);
        return sum + Number(participant?.actualAmount || 0);
      }, 0);

      const totalPaid = splitsForPerson.reduce((sum, split) => {
        const participant = (split.participants || []).find((p) => p.personId === person.id);
        return sum + Number(participant?.paidAmount || 0);
      }, 0);

      const totalOverpaid = splitsForPerson.reduce((sum, split) => {
        const participant = (split.participants || []).find((p) => p.personId === person.id);
        return sum + Number(participant?.overpaidAmount || 0);
      }, 0);

      const hasExpenses = splitsForPerson.length > 0;
      const hasUnpaid = splitsForPerson.some((split) =>
        (split.participants || []).some(
          (participant) => participant.personId === person.id && Number(participant.remainingAmount || 0) > 0.01,
        ),
      );
      const hasDueSoon = splitsForPerson.some((split) => {
        const participant = (split.participants || []).find((p) => p.personId === person.id);
        const d = daysUntil(split.dueDate);
        return participant && Number(participant.remainingAmount || 0) > 0.01 && d !== null && d >= 0 && d <= 7;
      });
      const hasOverdue = splitsForPerson.some((split) => {
        const participant = (split.participants || []).find((p) => p.personId === person.id);
        const d = daysUntil(split.dueDate);
        return participant && Number(participant.remainingAmount || 0) > 0.01 && d !== null && d < 0;
      });
      const hasOverpaid = totalOverpaid > 0.01;

      switch (statusFilter) {
        case "all":
          return true;
        case "remaining":
          return hasUnpaid;
        case "split_done":
          return hasExpenses;
        case "not_split":
          return !hasExpenses;
        case "overdue":
          return hasOverdue;
        case "due_soon":
          return hasDueSoon;
        case "overpaid":
          return hasOverpaid;
        default:
          return true;
      }
    });

    return [...list].sort((a, b) => {
      const splitsA = hydratedSplits.filter((split) => (split.participants || []).some((p) => p.personId === a.id));
      const splitsB = hydratedSplits.filter((split) => (split.participants || []).some((p) => p.personId === b.id));
      if (sortBy === "due_soon") {
        const nextA = Math.min(...splitsA.map((split) => {
          const d = daysUntil(split.dueDate);
          return d === null ? 99999 : d;
        }), 99999);
        const nextB = Math.min(...splitsB.map((split) => {
          const d = daysUntil(split.dueDate);
          return d === null ? 99999 : d;
        }), 99999);
        return nextA - nextB;
      }
      if (sortBy === "remaining_desc") {
        const remainA = splitsA.reduce((s, split) => {
          const p = (split.participants || []).find((x) => x.personId === a.id);
          return s + Number(p?.remainingAmount || 0);
        }, 0);
        const remainB = splitsB.reduce((s, split) => {
          const p = (split.participants || []).find((x) => x.personId === b.id);
          return s + Number(p?.remainingAmount || 0);
        }, 0);
        return remainB - remainA;
      }
      return a.name.localeCompare(b.name, "th");
    });
  }, [peopleOnly, hydratedSplits, statusFilter, sortBy]);

  return (
    <div style={{ fontFamily: "'Noto Sans Thai','Sarabun',sans-serif", minHeight: "100vh", background: "#f8f9fb" }}>
      <div style={{ background: "linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)", padding: "20px 20px 16px" }}>
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10, gap: 12, flexWrap: "wrap" }}>
            <div>
              <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                <div style={{ width: 34, height: 34, borderRadius: 9, background: "#6366f1", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>💎</div>
                <span style={{ fontSize: 20, fontWeight: 800, color: "#fff", letterSpacing: "-0.5px" }}>FinFlow</span>
                <span style={{ fontSize: 11, padding: "2px 8px", background: "rgba(255,255,255,0.12)", borderRadius: 99, color: "rgba(255,255,255,0.7)", letterSpacing: "0.05em" }}>SPLIT</span>
              </div>
              <p style={{ margin: "4px 0 0 44px", fontSize: 12, color: "rgba(255,255,255,0.5)" }}>{candidateTransactions.length} รายการร่วมจ่าย/คนอื่นจ่ายแทน · {peopleOnly.length} คน (รวมตัวเรา)</p>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
                            <select
                value={filterMonth}
                onChange={(e) => setFilterMonth(e.target.value)}
                style={{
                  padding: "8px 12px",
                  borderRadius: 10,
                  border: "none",
                  fontSize: 12,
                  background: "rgba(255,255,255,0.12)",
                  color: "#fff",
                  fontFamily: "inherit",
                  cursor: "pointer",
                  outline: "none",
                }}
              >
                <option value="" style={{ color: "#1a1a2e" }}>ทุกเดือน</option>
                {monthOptions.map((month) => (
                  <option key={month.value} value={month.value} style={{ color: "#1a1a2e" }}>{month.label}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
      </div>

      <div style={{ maxWidth: 900, margin: "0 auto", padding: "20px 16px 60px" }}>
        <SummaryOverview
          hydratedSplits={hydratedSplits}
          transactions={candidateTransactions}
          payments={payments}
          statusFilter={statusFilter}
          onSelectStatus={(key) => setStatusFilter((prev) => (prev === key ? "all" : key))}
        />

        <div style={{ display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap", alignItems: "center" }}>
          <Pill active={view === "transactions"} onClick={() => setView("transactions")} color="#6366f1">✂️ รายการแบ่งจ่าย</Pill>
          <Pill active={view === "people"} onClick={() => setView("people")} color="#8b5cf6">👥 Dashboard แต่ละคน</Pill>
          <select
            value={sortBy}
            onChange={(e) => setSortBy(e.target.value)}
            style={{
              padding: "6px 12px",
              borderRadius: 99,
              fontSize: 12,
              fontWeight: 600,
              border: "1.5px solid #e5e7eb",
              background: "#fff",
              color: "#6b7280",
              cursor: "pointer",
            }}
          >
            <option value="default">เรียงตามค่าเริ่มต้น</option>
            <option value="remaining_desc">ค้างมากสุดก่อน</option>
            <option value="due_soon">ใกล้ครบกำหนดก่อน</option>
          </select>
          {statusFilter !== "all" && (
            <button
              onClick={() => setStatusFilter("all")}
              style={{
                marginLeft: 4,
                padding: "5px 12px",
                borderRadius: 99,
                fontSize: 12,
                fontWeight: 600,
                border: "1.5px solid #e5e7eb",
                background: "#fff",
                color: "#6b7280",
                cursor: "pointer",
              }}
            >
              ล้างตัวกรอง
            </button>
          )}
        </div>

        {view === "transactions" ? (
          filteredTransactions.length === 0 ? (
            <div style={{ textAlign: "center", padding: "60px 20px", color: "#9ca3af" }}>
              <div style={{ fontSize: 48, marginBottom: 12 }}>✂️</div>
              <p style={{ margin: 0, fontSize: 15, fontWeight: 600, color: "#6b7280" }}>ยังไม่มีรายการร่วมจ่าย</p>
              <p style={{ margin: "6px 0 0", fontSize: 13 }}>ไปที่ Transaction แล้วเลือกผู้จ่ายเป็น “ร่วมกัน” หรือเลือกชื่อคนที่จ่ายแทน</p>
            </div>
          ) : (
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {filteredTransactions.map((tx) => (
                <TxSplitRow
                  key={tx.id}
                  tx={tx}
                  split={splitByTxId[tx.id]}
                  config={config}
                  payments={payments}
                  onEdit={(targetTx, targetSplit) => setEditTarget({ tx: targetTx, split: targetSplit })}
                  onRecordPayment={(split, personId) => setPayTarget({ split, personId })}
                />
              ))}
            </div>
          )
        ) : peopleOnly.length === 0 ? (
          <div style={{ textAlign: "center", padding: "60px 20px", color: "#9ca3af" }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>👥</div>
            <p style={{ margin: 0, fontSize: 15, fontWeight: 600, color: "#6b7280" }}>ยังไม่มีบุคคลในระบบ</p>
            <p style={{ margin: "6px 0 0", fontSize: 13 }}>ไปที่ Setup → บุคคล เพื่อเพิ่มชื่อ</p>
          </div>
        ) : (
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: 14 }}>
            {filteredPeople.length === 0 ? (
              <div style={{ gridColumn: "1 / -1", textAlign: "center", padding: "60px 20px", color: "#9ca3af" }}>
                <div style={{ fontSize: 48, marginBottom: 12 }}>🔎</div>
                <p style={{ margin: 0, fontSize: 15, fontWeight: 600, color: "#6b7280" }}>ไม่พบคนที่ตรงกับสถานะนี้</p>
                <p style={{ margin: "6px 0 0", fontSize: 13 }}>ลองเปลี่ยนตัวกรองด้านบนหรือกดล้างตัวกรอง</p>
              </div>
            ) : (
              filteredPeople.map((person) => (
              <PersonDebtCard
                key={person.id}
                person={person}
                hydratedSplits={hydratedSplits}
                transactions={candidateTransactions}
                payments={payments}
                onRecordPayment={(split, personId) => setPayTarget({ split, personId })}
                onPayAll={handlePayAllForPerson}
              />
            )))}
          </div>
        )}
      </div>

      {editTarget && (
        <SplitEditor tx={editTarget.tx} split={editTarget.split} config={config} onSave={handleSaveSplit} onClose={() => setEditTarget(null)} />
      )}

      {payTarget && (
        <RecordPaymentModal
          split={payTarget.split}
          tx={candidateTransactions.find((tx) => tx.id === payTarget.split.txId)}
          personId={payTarget.personId}
          config={config}
          existingPayments={payments}
          onSave={handleSavePayment}
          onUpdatePayment={handleUpdatePayment}
          onDeletePaymentRequest={(paymentId) => setDeletePaymentId(paymentId)}
          onClose={() => setPayTarget(null)}
        />
      )}

      {deletePaymentId && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 300, padding: 16 }}>
          <div style={{ background: "#fff", borderRadius: 16, maxWidth: 360, width: "100%", boxShadow: "0 20px 60px rgba(0,0,0,0.2)", padding: 24 }}>
            <h3 style={{ margin: "0 0 8px", fontSize: 16, fontWeight: 700, color: "#1a1a2e" }}>🗑️ ลบประวัติการชำระ</h3>
            <p style={{ margin: "0 0 18px", fontSize: 13, color: "#6b7280" }}>คุณต้องการลบรายการชำระนี้ใช่ไหม</p>
            <div style={{ display: "flex", gap: 10 }}>
              <button onClick={() => setDeletePaymentId(null)} style={{ flex: 1, padding: 10, borderRadius: 10, border: "1.5px solid #e5e7eb", background: "#fff", color: "#6b7280", cursor: "pointer", fontWeight: 600 }}>ยกเลิก</button>
              <button onClick={() => handleDeletePayment(deletePaymentId)} style={{ flex: 1, padding: 10, borderRadius: 10, border: "none", background: "#dc2626", color: "#fff", cursor: "pointer", fontWeight: 700 }}>ลบ</button>
            </div>
          </div>
        </div>
      )}

      {/* Confirm dialog: ยอดของคนเปลี่ยนหลังจ่ายแล้ว */}
      {confirmSplitChange && (
        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 400, padding: 16 }}>
          <div style={{ background: "#fff", borderRadius: 16, maxWidth: 420, width: "100%", boxShadow: "0 20px 60px rgba(0,0,0,0.25)", padding: 24 }}>
            <h3 style={{ margin: "0 0 6px", fontSize: 16, fontWeight: 700, color: "#1a1a2e" }}>⚠️ ยอดของคนต่อไปนี้เปลี่ยนไป</h3>
            <p style={{ margin: "0 0 14px", fontSize: 13, color: "#6b7280" }}>
              บุคคลด้านล่างเคยชำระเงินมาแล้ว การเปลี่ยนยอดจะทำให้ระบบแสดง overpaid หรือ underpaid อัตโนมัติ
            </p>

            {/* รายละเอียดแต่ละคนที่ได้รับผล */}
            <div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 18 }}>
              {confirmSplitChange.affectedPeople.map((p) => {
                const diff = p.newAmt - p.oldAmt;
                const allPeople = getAllPeople(config);
                const person = allPeople.find((x) => x.id === p.personId) || { name: p.name, color: "#9ca3af" };
                return (
                  <div key={p.personId} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", background: "#fef9ec", borderRadius: 10, border: "1px solid #fde68a" }}>
                    <Avatar person={person} size={32} />
                    <div style={{ flex: 1 }}>
                      <div style={{ fontWeight: 600, fontSize: 13, color: "#1a1a2e" }}>{p.name}</div>
                      <div style={{ fontSize: 12, color: "#92400e" }}>
                        ฿{Math.round(p.oldAmt).toLocaleString()} → ฿{Math.round(p.newAmt).toLocaleString()}
                        <span style={{ marginLeft: 6, fontWeight: 700, color: diff > 0 ? "#ef4444" : "#22c55e" }}>
                          ({diff > 0 ? "+" : ""}{Math.round(diff).toLocaleString()})
                        </span>
                      </div>
                    </div>
                    <Badge color={diff > 0 ? "#ef4444" : "#22c55e"}>
                      {diff > 0 ? "จ่ายไม่ครบ" : "จ่ายเกิน"}
                    </Badge>
                  </div>
                );
              })}
            </div>

            <p style={{ margin: "0 0 16px", fontSize: 12, color: "#6b7280", background: "#f9fafb", padding: "10px 12px", borderRadius: 8 }}>
              💡 ระบบจะ <strong>เก็บประวัติการชำระเดิมไว้</strong> และแสดง overpaid/underpaid ในหน้า Dashboard — สามารถเข้าไปแก้ไข record ได้ภายหลัง
            </p>

            <div style={{ display: "flex", gap: 10 }}>
              <button
                onClick={() => setConfirmSplitChange(null)}
                style={{ flex: 1, padding: 11, borderRadius: 10, border: "1.5px solid #e5e7eb", background: "#fff", color: "#6b7280", cursor: "pointer", fontWeight: 600, fontSize: 13 }}
              >
                ยกเลิก (แก้ใหม่)
              </button>
              <button
                onClick={() => commitSaveSplit(confirmSplitChange.splitData)}
                style={{ flex: 2, padding: 11, borderRadius: 10, border: "none", background: "#f59e0b", color: "#fff", cursor: "pointer", fontWeight: 700, fontSize: 13 }}
              >
                ยืนยัน บันทึกการเปลี่ยนแปลง
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
